apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: dep1
    name: dep1
    namespace: default
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: dep1
        version: 4.0
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: dep1
      spec:
        containers:
        - image: satyaprasad3186/mytomcat:4.0
          imagePullPolicy: IfNotPresent
          name: mytomcat
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler